version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    network_mode: "host"
    image: rabbitmq:3-management
    restart: unless-stopped
  zookeeper:
    container_name: zookeeper
    network_mode: "host"
    image: zookeeper:3.6
    restart: unless-stopped
    volumes:
      - ./zookeeper:/conf
  redis:
    container_name: redis
    image: redis
    network_mode: "host"
    restart: unless-stopped
  mysql:
    container_name: mysql
    image: mysql:5
    network_mode: "host"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./mysql/data:/var/lib/mysql
