version: '2'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: my-rabbit
    image: rabbitmq:3.6.14-management
    ports:
    - "5672:5672"
    - "15672:15672"
  zookeeper:
    container_name: zookeeper
    hostname: my-zookeeper
    image: zookeeper:3.4.11
    ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"